FROM registry.cn-shenzhen.aliyuncs.com/efucloud-public/nginx:1.29.4-alpine

ARG GIT_COMMIT
ARG BUILD_DATE

LABEL org.opencontainers.image.source=https://github.com/efucloud/kube-keeper-saas
LABEL org.opencontainers.image.revision=${GIT_COMMIT}
LABEL org.opencontainers.image.created=${BUILD_DATE}

# 从 builder 复制构建产物
COPY ./dist /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
