export default [
  {
    icon: "dashboard",
    name: "dashboard",
    path: "/kubernetes/namespace/dashboard",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "overview",
        path: "/kubernetes/namespace/dashboard/overview",
        component: "./kubernetes/namespace/dashboard/overview",
        access: "clusterNamespaceAccess",
      },
      {
        name: "workload",
        path: "/kubernetes/namespace/dashboard/workload",
        component: "./kubernetes/namespace/dashboard/workload",
        access: "clusterNamespaceAccess",
      },
    ],
  },
  {
    name: "workload",
    icon: "CloudServerOutlined",
    path: "/kubernetes/namespace/workload",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "pod",
        path: "/kubernetes/namespace/workload/pods",
        component: "./kubernetes/namespace/workload/pod",
        access: "clusterNamespaceAccess",
      },
      {
        name: "pod",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/pods/:name",
        component: "./kubernetes/namespace/workload/pod/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "pod",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/pods/:name/:action",
        component: "./kubernetes/namespace/workload/pod/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "deployment",
        path: "/kubernetes/namespace/workload/deployments",
        component: "./kubernetes/namespace/workload/deployment",
        access: "clusterNamespaceAccess",
      },
      {
        name: "deployment",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/deployments/:name",
        component: "./kubernetes/namespace/workload/deployment/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "deployment",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/deployments/:name/:action",
        component: "./kubernetes/namespace/workload/deployment/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "deployment",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/deployments/:name/:action/step",
        component: "./kubernetes/namespace/workload/deployment/step_form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "statefulset",
        path: "/kubernetes/namespace/workload/statefulsets",
        component: "./kubernetes/namespace/workload/statefulset",
        access: "clusterNamespaceAccess",
      },
      {
        name: "statefulset",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/statefulsets/:name",
        component: "./kubernetes/namespace/workload/statefulset/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "statefulset",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/statefulsets/:name/:action",
        component: "./kubernetes/namespace/workload/statefulset/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "statefulset",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/statefulsets/:name/:action/step",
        component: "./kubernetes/namespace/workload/statefulset/step_form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "daemonset",
        path: "/kubernetes/namespace/workload/daemonsets",
        component: "./kubernetes/namespace/workload/daemonset",
        access: "clusterNamespaceAccess",
      },
      {
        name: "daemonset",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/daemonsets/:name",
        component: "./kubernetes/namespace/workload/daemonset/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "daemonset",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/daemonsets/:name/:action",
        component: "./kubernetes/namespace/workload/daemonset/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "daemonset",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/daemonsets/:name/:action/step",
        component: "./kubernetes/namespace/workload/daemonset/step_form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "job",
        path: "/kubernetes/namespace/workload/jobs",
        component: "./kubernetes/namespace/workload/job",
        access: "clusterNamespaceAccess",
      },
      {
        name: "job",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/jobs/:name",
        component: "./kubernetes/namespace/workload/job/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "job",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/jobs/:name/:action",
        component: "./kubernetes/namespace/workload/job/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "cronjob",
        path: "/kubernetes/namespace/workload/cronjobs",
        component: "./kubernetes/namespace/workload/cronjob",
        access: "clusterNamespaceAccess",
      },
      {
        name: "cronjob",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/cronjobs/:name",
        component: "./kubernetes/namespace/workload/cronjob/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "cronjob",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/cronjobs/:name/:action",
        component: "./kubernetes/namespace/workload/cronjob/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "replicaset",
        path: "/kubernetes/namespace/workload/replicasets",
        component: "./kubernetes/namespace/workload/replicaset",
        access: "clusterNamespaceAccess",
      },
      {
        name: "replicaset",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/replicasets/:name",
        component: "./kubernetes/namespace/workload/replicaset/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "replicaset",
        hideInMenu: true,
        path: "/kubernetes/namespace/workload/replicasets/:name/:action",
        component: "./kubernetes/namespace/workload/replicaset/text",
        access: "clusterNamespaceAccess",
      },
    ],
  },
  {
    name: "config",
    icon: "ToolOutlined",
    path: "/kubernetes/namespace/config",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "configmap",
        path: "/kubernetes/namespace/config/configmaps",
        component: "./kubernetes/namespace/config/configmap",
        access: "clusterNamespaceAccess",
      },
      {
        name: "configmap",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/configmaps/:name",
        component: "./kubernetes/namespace/config/configmap/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "configmap",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/configmaps/create/text",
        component: "./kubernetes/namespace/config/configmap/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "configmap",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/configmaps/:name/:action",
        component: "./kubernetes/namespace/config/configmap/form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "secret",
        path: "/kubernetes/namespace/config/secrets",
        component: "./kubernetes/namespace/config/secret",
        access: "clusterNamespaceAccess",
      },
      {
        name: "secret",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/secrets/:name",
        component: "./kubernetes/namespace/config/secret/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "secret",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/secrets/create/text",
        component: "./kubernetes/namespace/config/secret/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "secret",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/secrets/:name/:action",
        component: "./kubernetes/namespace/config/secret/form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "resourcequota",
        path: "/kubernetes/namespace/config/resourcequotas",
        component: "./kubernetes/namespace/config/resourcequota",
        access: "clusterNamespaceAccess",
      },
      {
        name: "resourcequota",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/resourcequotas/:name/:action",
        component: "./kubernetes/namespace/config/resourcequota/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "limitrange",
        path: "/kubernetes/namespace/config/limitranges",
        component: "./kubernetes/namespace/config/limitrange",
        access: "clusterNamespaceAccess",
      },
      {
        name: "limitrange",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/limitranges/:name/:action",
        component: "./kubernetes/namespace/config/limitrange/text",
        access: "clusterNamespaceAccess",
      },
    ],
  },

  {
    name: "network",
    icon: "GlobalOutlined",
    path: "/kubernetes/namespace/networks",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "service",
        path: "/kubernetes/namespace/networks/services",
        component: "./kubernetes/namespace/networks/service",
        access: "clusterNamespaceAccess",
      },
      {
        name: "service",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/services/create/text",
        component: "./kubernetes/namespace/networks/service/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "service",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/services/:name/:action/text",
        component: "./kubernetes/namespace/networks/service/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "service",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/services/:name/:action",
        component: "./kubernetes/namespace/networks/service/form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "service",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/services/:name",
        component: "./kubernetes/namespace/networks/service/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "ingress",
        path: "/kubernetes/namespace/networks/ingresses",
        component: "./kubernetes/namespace/networks/ingress",
        access: "clusterNamespaceAccess",
      },
      {
        name: "ingress",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/ingresses/create/text",
        component: "./kubernetes/namespace/networks/ingress/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "ingress",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/ingresses/:name/:action/text",
        component: "./kubernetes/namespace/networks/ingress/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "ingress",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/ingresses/:name/:action",
        component: "./kubernetes/namespace/networks/ingress/form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "ingress",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/ingresses/:name",
        component: "./kubernetes/namespace/networks/ingress/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "EndpointSlice",
        path: "/kubernetes/namespace/networks/endpoint_slices",
        component: "./kubernetes/namespace/networks/endpoint_slice",
        access: "clusterResourceEndpointSliceAccess",
      },
      {
        name: "EndpointSlice",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/endpoint_slices/:name/:action",
        component: "./kubernetes/namespace/networks/endpoint_slice/text",
        access: "clusterResourceEndpointSliceAccess",
      },
      {
        name: "endpoint",
        path: "/kubernetes/namespace/networks/endpoints",
        component: "./kubernetes/namespace/networks/endpoint",
      },
      {
        name: "endpoint",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/endpoints/:name/:action",
        component: "./kubernetes/namespace/networks/endpoint/text",
        access: "clusterNamespaceAccess",
      },
    ],
  },

  {
    name: "access",
    icon: "usergroupAddOutlined",
    path: "/kubernetes/namespace/access",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "accountPermission",
        path: "/kubernetes/namespace/access/account",
        component: "./kubernetes/namespace/access/account",
      },
      {
        name: "serviceaccount",
        path: "/kubernetes/namespace/access/serviceaccounts",
        component: "./kubernetes/namespace/access/serviceaccount",
      },
      {
        name: "serviceaccount",
        hideInMenu: true,
        path: "/kubernetes/namespace/access/serviceaccounts/:name/:action",
        component: "./kubernetes/namespace/access/serviceaccount/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "role",
        path: "/kubernetes/namespace/access/roles",
        component: "./kubernetes/namespace/access/role",
      },
      {
        name: "role",
        hideInMenu: true,
        path: "/kubernetes/namespace/access/roles/:name/:action",
        component: "./kubernetes/namespace/access/role/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "rolebinding",
        path: "/kubernetes/namespace/access/rolebindings",
        component: "./kubernetes/namespace/access/rolebinding",
      },
      {
        name: "role",
        hideInMenu: true,
        path: "/kubernetes/namespace/access/rolebindings/:name/:action",
        component: "./kubernetes/namespace/access/rolebinding/text",
        access: "clusterNamespaceAccess",
      },
    ],
  },
  {
    name: "storage",
    icon: "DatabaseOutlined",
    path: "/kubernetes/namespace/storage",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "persistentVolumeClaim",
        path: "/kubernetes/namespace/storage/pvc",
        component: "./kubernetes/namespace/storage/pvc",
      },
      {
        name: "persistentVolumeClaim",
        hideInMenu: true,
        path: "/kubernetes/namespace/storage/pvc/:name/:action",
        component: "./kubernetes/namespace/storage/pvc/text",
        access: "clusterNamespaceAccess",
      },
    ],
  },
  {
    name: "policy",
    icon: "PicRightOutlined",
    path: "/kubernetes/namespace/policy",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "networkpolicy",
        path: "/kubernetes/namespace/policy/networkpolicy",
        component: "./kubernetes/namespace/policy/networkpolicy",
      },
      {
        name: "networkpolicy",
        hideInMenu: true,
        path: "/kubernetes/namespace/policy/networkpolicy/:name/:action",
        component: "./kubernetes/namespace/policy/networkpolicy/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "hpa",
        path: "/kubernetes/namespace/policy/hpa",
        component: "./kubernetes/namespace/policy/hpa",
      },
      {
        name: "hpa",
        hideInMenu: true,
        path: "/kubernetes/namespace/policy/hpa/:name/:action",
        component: "./kubernetes/namespace/policy/hpa/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "poddisruptionbudget",
        path: "/kubernetes/namespace/policy/poddisruptionbudgets",
        component: "./kubernetes/namespace/policy/poddisruptionbudget",
      },
      {
        name: "poddisruptionbudget",
        hideInMenu: true,
        path: "/kubernetes/namespace/policy/poddisruptionbudgets/:name/:action",
        component: "./kubernetes/namespace/policy/poddisruptionbudget/text",
        access: "clusterNamespaceAccess",
      },
    ],
  },
  {
    name: "monitor",
    icon: "RadarChartOutlined",
    path: "/kubernetes/namespace/monitor",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "event",
        path: "/kubernetes/namespace/monitor/events",
        component: "./kubernetes/namespace/monitor/event",
      },
      {
        name: "terminalAuditLog",
        path: "/kubernetes/namespace/monitor/terminal",
        component: "./kubernetes/cluster/monitor/terminal",
      },
    ],
  },
  {
    name: "monitor",
    hideInMenu: true,
    menuRender: false,
    path: "/kubernetes/namespace/application-instance/:id",
    access: "clusterNamespaceAccess",
    component: "./kubernetes/namespace/application_instance/detail",
  },

  {
    name: "config",
    icon: "ToolOutlined",
    path: "/kubernetes/namespace/config",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "configmap",
        path: "/kubernetes/namespace/config/configmaps",
        component: "./kubernetes/namespace/config/configmap",
      },
      {
        name: "configmap",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/configmaps/:name",
        component: "./kubernetes/namespace/config/configmap/detail",
      },
      {
        name: "configmap",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/configmaps/create/text",
        component: "./kubernetes/namespace/config/configmap/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "configmap",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/configmaps/:name/:action",
        component: "./kubernetes/namespace/config/configmap/form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "secret",
        path: "/kubernetes/namespace/config/secrets",
        component: "./kubernetes/namespace/config/secret",
      },
      {
        name: "secret",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/secrets/:name",
        component: "./kubernetes/namespace/config/secret/detail",
      },
      {
        name: "secret",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/secrets/create/text",
        component: "./kubernetes/namespace/config/secret/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "secret",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/secrets/:name/:action",
        component: "./kubernetes/namespace/config/secret/form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "resourcequota",
        path: "/kubernetes/namespace/config/resourcequotas",
        component: "./kubernetes/namespace/config/resourcequota",
      },
      {
        name: "resourcequota",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/resourcequotas/:name/:action",
        component: "./kubernetes/namespace/config/resourcequota/text",
      },
      {
        name: "limitrange",
        path: "/kubernetes/namespace/config/limitranges",
        component: "./kubernetes/namespace/config/limitrange",
      },
      {
        name: "limitrange",
        hideInMenu: true,
        path: "/kubernetes/namespace/config/limitranges/:name/:action",
        component: "./kubernetes/namespace/config/limitrange/text",
      },
    ],
  },

  {
    name: "network",
    icon: "GlobalOutlined",
    path: "/kubernetes/namespace/networks",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "service",
        path: "/kubernetes/namespace/networks/services",
        component: "./kubernetes/namespace/networks/service",
      },
      {
        name: "service",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/services/create/text",
        component: "./kubernetes/namespace/networks/service/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "service",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/services/:name/:action",
        component: "./kubernetes/namespace/networks/service/form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "service",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/services/:name",
        component: "./kubernetes/namespace/networks/service/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "ingress",
        path: "/kubernetes/namespace/networks/ingresses",
        component: "./kubernetes/namespace/networks/ingress",
      },
      {
        name: "ingress",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/ingresses/create/text",
        component: "./kubernetes/namespace/networks/ingress/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "ingress",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/ingresses/:name/:action",
        component: "./kubernetes/namespace/networks/ingress/form",
        access: "clusterNamespaceAccess",
      },
      {
        name: "ingress",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/ingresses/:name",
        component: "./kubernetes/namespace/networks/ingress/detail",
        access: "clusterNamespaceAccess",
      },
      {
        name: "EndpointSlice",
        path: "/kubernetes/namespace/networks/endpoint_slices",
        component: "./kubernetes/namespace/networks/endpoint_slice",
        access: "clusterResourceEndpointSliceAccess",
      },
      {
        name: "EndpointSlice",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/endpoint_slices/:name/:action",
        component: "./kubernetes/namespace/networks/endpoint_slice/text",
        access: "clusterResourceEndpointSliceAccess",
      },
      {
        name: "endpoint",
        path: "/kubernetes/namespace/networks/endpoints",
        component: "./kubernetes/namespace/networks/endpoint",
      },
      {
        name: "endpoint",
        hideInMenu: true,
        path: "/kubernetes/namespace/networks/endpoints/:name/:action",
        component: "./kubernetes/namespace/networks/endpoint/text",
      },
    ],
  },

  {
    name: "access",
    icon: "usergroupAddOutlined",
    path: "/kubernetes/namespace/access",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "accountPermission",
        path: "/kubernetes/namespace/access/account",
        component: "./kubernetes/namespace/access/account",
      },
      {
        name: "serviceaccount",
        path: "/kubernetes/namespace/access/serviceaccounts",
        component: "./kubernetes/namespace/access/serviceaccount",
      },
      {
        name: "serviceaccount",
        hideInMenu: true,
        path: "/kubernetes/namespace/access/serviceaccounts/:name/:action",
        component: "./kubernetes/namespace/access/serviceaccount/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "role",
        path: "/kubernetes/namespace/access/roles",
        component: "./kubernetes/namespace/access/role",
      },
      {
        name: "role",
        hideInMenu: true,
        path: "/kubernetes/namespace/access/roles/:name/:action",
        component: "./kubernetes/namespace/access/role/text",
        access: "clusterNamespaceAccess",
      },
      {
        name: "rolebinding",
        path: "/kubernetes/namespace/access/rolebindings",
        component: "./kubernetes/namespace/access/rolebinding",
      },
      {
        name: "role",
        hideInMenu: true,
        path: "/kubernetes/namespace/access/rolebindings/:name/:action",
        component: "./kubernetes/namespace/access/rolebinding/text",
        access: "clusterNamespaceAccess",
      },
    ],
  },
  {
    name: "storage",
    icon: "DatabaseOutlined",
    path: "/kubernetes/namespace/storage",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "persistentVolumeClaim",
        path: "/kubernetes/namespace/storage/pvc",
        component: "./kubernetes/namespace/storage/pvc",
      },
      {
        name: "persistentVolumeClaim",
        hideInMenu: true,
        path: "/kubernetes/namespace/storage/pvc/:name/:action",
        component: "./kubernetes/namespace/storage/pvc/text",
      },
    ],
  },
  {
    name: "policy",
    icon: "PicRightOutlined",
    path: "/kubernetes/namespace/policy",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "networkpolicy",
        path: "/kubernetes/namespace/policy/networkpolicy",
        component: "./kubernetes/namespace/policy/networkpolicy",
      },
      {
        name: "networkpolicy",
        hideInMenu: true,
        path: "/kubernetes/namespace/policy/networkpolicy/:name/:action",
        component: "./kubernetes/namespace/policy/networkpolicy/text",
      },
      {
        name: "hpa",
        path: "/kubernetes/namespace/policy/hpa",
        component: "./kubernetes/namespace/policy/hpa",
      },
      {
        name: "hpa",
        hideInMenu: true,
        path: "/kubernetes/namespace/policy/hpa/:name/:action",
        component: "./kubernetes/namespace/policy/hpa/text",
      },
      {
        name: "poddisruptionbudget",
        path: "/kubernetes/namespace/policy/poddisruptionbudgets",
        component: "./kubernetes/namespace/policy/poddisruptionbudget",
      },
      {
        name: "poddisruptionbudget",
        hideInMenu: true,
        path: "/kubernetes/namespace/policy/poddisruptionbudgets/:name/:action",
        component: "./kubernetes/namespace/policy/poddisruptionbudget/text",
      },
    ],
  },
  {
    name: "monitor",
    icon: "RadarChartOutlined",
    path: "/kubernetes/namespace/monitor",
    access: "clusterNamespaceAccess",
    routes: [
      {
        name: "event",
        path: "/kubernetes/namespace/monitor/events",
        component: "./kubernetes/namespace/monitor/event",
      },
      {
        name: "event",
        hideInMenu: true,
        path: "/kubernetes/namespace/monitor/events/:name/:action",
        component: "./kubernetes/namespace/monitor/event/text",
      },
      {
        name: "terminalAuditLog",
        path: "/kubernetes/namespace/monitor/terminal",
        component: "./kubernetes/cluster/monitor/terminal",
      },
    ],
  },
  {
    name: "monitor",
    hideInMenu: true,
    menuRender: false,
    path: "/kubernetes/namespace/application-instance/:id",
    access: "clusterNamespaceAccess",
    component: "./kubernetes/namespace/application_instance/detail",
  },
];
