export default [
  {
    icon: "terminal",
    name: "terminal",
    menuRender: false,
    hideInMenu: true,
    path: "/kubernetes/cluster/terminal",
    access: "clusterAccess",
    component: "./kubernetes/cluster/terminal",
  },
  {
    icon: "dashboard",
    name: "dashboard",
    path: "/kubernetes/cluster/dashboard",
    access: "clusterAccess",
    routes: [
      {
        name: "overview",
        path: "/kubernetes/cluster/dashboard/overview",
        component: "./kubernetes/cluster/dashboard",
        access: "clusterAccess",
      },
      {
        name: "ApiServer",
        path: "/kubernetes/cluster/dashboard/api-server",
        component: "./kubernetes/cluster/dashboard/apiserver",
        access: "clusterAccess",
      },
      {
        name: "cluster",
        path: "/kubernetes/cluster/dashboard/cluster",
        component: "./kubernetes/cluster/dashboard/cluster",
        access: "clusterAccess",
      },
    ],
  },

  {
    icon: "SafetyCertificateOutlined",
    name: "clusterPermission",
    path: "/kubernetes/cluster/permission",
    access: "clusterAccess",
    routes: [
      {
        name: "clusterAccount",
        path: "/kubernetes/cluster/permission/cluster-account",
        component: "./kubernetes/permission/cluster_account",
        access: "clusterAccess",
      },
      {
        name: "clusterAccount",
        path: "/kubernetes/cluster/permission/cluster-account/rbac-view/:accountId",
        component: "./kubernetes/permission/cluster_account/rbac_view",
        access: "clusterAccess",
        hideInMenu: true,
      },
      {
        name: "clusterAccount",
        path: "/kubernetes/cluster/permission/cluster-account/detail/:id",
        component: "./kubernetes/permission/cluster_account/detail",
        access: "clusterAccess",
        hideInMenu: true,
      },
      {
        name: "accountPermission",
        path: "/kubernetes/cluster/permission/account-permission",
        component: "./kubernetes/permission/permission",
        access: "clusterAccess",
      },
    ],
  },
  {
    icon: "BarsOutlined",
    name: "clusterNode",
    path: "/kubernetes/cluster/node",
    component: "./kubernetes/cluster/node",
    access: "clusterAccess",
  },
  {
    name: "clusterNode",
    hideInMenu: true,
    path: "/kubernetes/cluster/node/:node",
    component: "./kubernetes/cluster/node/detail",
    access: "clusterAccess",
  },
  {
    icon: "BorderOuterOutlined",
    name: "clusterNamespace",
    path: "/kubernetes/cluster/namespace",
    component: "./kubernetes/cluster/namespace",
    access: "clusterAccess",
  },

  {
    name: "workload",
    icon: "CloudServerOutlined",
    path: "/kubernetes/cluster/workload",
    access: "clusterAccess",
    routes: [
      {
        name: "pod",
        path: "/kubernetes/cluster/workload/pods",
        component: "./kubernetes/namespace/workload/pod",
        access: "clusterAccess",
      },
      {
        name: "pod",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/pods/:name/:action",
        component: "./kubernetes/namespace/workload/pod/text",
        access: "clusterAccess",
      },
      {
        name: "deployment",
        path: "/kubernetes/cluster/workload/deployments",
        component: "./kubernetes/namespace/workload/deployment",
        access: "clusterAccess",
      },
      {
        name: "deployment",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/deployments/:name/:action",
        component: "./kubernetes/namespace/workload/deployment/text",
        access: "clusterAccess",
      },
      {
        name: "deployment",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/deployments/:name/:action/step",
        component: "./kubernetes/namespace/workload/deployment/step_form",
        access: "clusterAccess",
      },
      {
        name: "deployment",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/deployments/create/text",
        component: "./kubernetes/namespace/workload/deployment/text",
        access: "clusterAccess",
      },
      {
        name: "deployment",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/deployments/create/text",
        component: "./kubernetes/namespace/workload/deployment/step_form",
        access: "clusterAccess",
      },
      {
        name: "statefulset",
        path: "/kubernetes/cluster/workload/statefulsets",
        component: "./kubernetes/namespace/workload/statefulset",
        access: "clusterAccess",
      },
      {
        name: "statefulset",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/statefulsets/:name/:action/step",
        component: "./kubernetes/namespace/workload/statefulset/step_form",
        access: "clusterAccess",
      },
      {
        name: "statefulset",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/statefulsets/:name/:action",
        component: "./kubernetes/namespace/workload/statefulset/text",
        access: "clusterAccess",
      },
      {
        name: "statefulset",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/statefulsets/create/text",
        component: "./kubernetes/namespace/workload/statefulset/text",
        access: "clusterAccess",
      },

      {
        name: "daemonset",
        path: "/kubernetes/cluster/workload/daemonsets",
        component: "./kubernetes/namespace/workload/daemonset",
        access: "clusterAccess",
      },
      {
        name: "daemonset",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/daemonsets/:name/:action",
        component: "./kubernetes/namespace/workload/daemonset/text",
        access: "clusterAccess",
      },

      {
        name: "daemonset",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/daemonsets/create/text",
        component: "./kubernetes/namespace/workload/daemonset/text",
        access: "clusterAccess",
      },
      {
        name: "daemonset",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/daemonsets/:name/:action/step",
        component: "./kubernetes/namespace/workload/daemonset/step_form",
        access: "clusterAccess",
      },
      {
        name: "job",
        path: "/kubernetes/cluster/workload/jobs",
        component: "./kubernetes/namespace/workload/job",
        access: "clusterAccess",
      },
      {
        name: "job",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/jobs/:name/:action",
        component: "./kubernetes/namespace/workload/job/text",
        access: "clusterAccess",
      },
      {
        name: "job",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/jobs/create/text",
        component: "./kubernetes/namespace/workload/job/text",
        access: "clusterAccess",
      },
      {
        name: "cronjob",
        path: "/kubernetes/cluster/workload/cronjobs",
        component: "./kubernetes/namespace/workload/cronjob",
        access: "clusterAccess",
      },
      {
        name: "cronjob",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/cronjobs/:name/:action",
        component: "./kubernetes/namespace/workload/cronjob/text",
        access: "clusterAccess",
      },
      {
        name: "cronjob",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/cronjobs/create/text",
        component: "./kubernetes/namespace/workload/cronjob/text",
        access: "clusterAccess",
      },
      {
        name: "replicaset",
        path: "/kubernetes/cluster/workload/replicasets",
        component: "./kubernetes/namespace/workload/replicaset",
        access: "clusterAccess",
      },
      {
        name: "replicaset",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/replicasets/:name/:action",
        component: "./kubernetes/namespace/workload/replicaset/text",
        access: "clusterAccess",
      },
      {
        name: "replicaset",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/replicasets/create/text",
        component: "./kubernetes/namespace/workload/replicaset/text",
        access: "clusterAccess",
      },
      {
        name: "replicaset",
        hideInMenu: true,
        path: "/kubernetes/cluster/workload/replicasets/:name",
        component: "./kubernetes/namespace/workload/replicaset/detail",
        access: "clusterAccess",
      },
    ],
  },
  {
    name: "config",
    icon: "ToolOutlined",
    path: "/kubernetes/cluster/config",
    access: "clusterAccess",
    routes: [
      {
        name: "configmap",
        path: "/kubernetes/cluster/config/configmaps",
        component: "./kubernetes/namespace/config/configmap",
      },
      {
        name: "configmap",
        hideInMenu: true,
        path: "/kubernetes/cluster/config/configmaps/create/text",
        component: "./kubernetes/namespace/config/configmap/text",
      },
      {
        name: "configmap",
        hideInMenu: true,
        path: "/kubernetes/cluster/config/configmaps/:name/:action",
        component: "./kubernetes/namespace/config/configmap/form",
      },
      {
        name: "secret",
        path: "/kubernetes/cluster/config/secrets",
        component: "./kubernetes/namespace/config/secret",
      },
      {
        name: "secret",
        hideInMenu: true,
        path: "/kubernetes/cluster/config/secrets/create/text",
        component: "./kubernetes/namespace/config/secret/text",
      },
      {
        name: "secret",
        hideInMenu: true,
        path: "/kubernetes/cluster/config/secrets/:name/:action",
        component: "./kubernetes/namespace/config/secret/form",
      },
      {
        name: "resourcequota",
        path: "/kubernetes/cluster/config/resourcequotas",
        component: "./kubernetes/namespace/config/resourcequota",
      },
      {
        name: "resourcequota",
        hideInMenu: true,
        path: "/kubernetes/cluster/config/resourcequotas/:name/:action",
        component: "./kubernetes/namespace/config/resourcequota/text",
      },
      {
        name: "limitrange",
        path: "/kubernetes/cluster/config/limitranges",
        component: "./kubernetes/namespace/config/limitrange",
      },
      {
        name: "limitrange",
        hideInMenu: true,
        path: "/kubernetes/cluster/config/limitranges/:name/:action",
        component: "./kubernetes/namespace/config/limitrange/text",
      },
      {
        name: "validatingwebhookconfiguration",
        path: "/kubernetes/cluster/config/validatingwebhookconfigurations",
        component: "./kubernetes/cluster/config/validatingwebhookconfiguration",
      },
      {
        name: "validatingwebhookconfiguration",
        hideInMenu: true,
        path: "/kubernetes/cluster/config/validatingwebhookconfigurations/:name/:action",
        component:
          "./kubernetes/cluster/config/validatingwebhookconfiguration/text",
      },
      {
        name: "mutatingwebhookconfiguration",
        path: "/kubernetes/cluster/config/mutatingwebhookconfigurations",
        component: "./kubernetes/cluster/config/mutatingwebhookconfiguration",
      },
      {
        name: "mutatingwebhookconfiguration",
        hideInMenu: true,
        path: "/kubernetes/cluster/config/mutatingwebhookconfigurations/:name/:action",
        component:
          "./kubernetes/cluster/config/mutatingwebhookconfiguration/text",
      },
    ],
  },

  {
    icon: "GlobalOutlined",
    name: "network",
    path: "/kubernetes/cluster/networks",
    access: "clusterAccess",
    routes: [
      {
        name: "ingressClass",
        path: "/kubernetes/cluster/networks/ingressclasses",
        component: "./kubernetes/cluster/networks/ingress_class",
      },
      {
        name: "ingressClass",
        hideInMenu: true,
        path: "/kubernetes/cluster/networks/ingressclasses/create/text",
        component: "./kubernetes/cluster/networks/ingress_class/text",
      },
      {
        name: "service",
        path: "/kubernetes/cluster/networks/services",
        component: "./kubernetes/namespace/networks/service",
      },
      {
        name: "service",
        hideInMenu: true,
        path: "/kubernetes/cluster/networks/services/create/text",
        component: "./kubernetes/namespace/networks/service/text",
      },
      {
        name: "service",
        hideInMenu: true,
        path: "/kubernetes/cluster/networks/services/:name/:action",
        component: "./kubernetes/namespace/networks/service/form",
      },

      {
        name: "ingress",
        path: "/kubernetes/cluster/networks/ingresses",
        component: "./kubernetes/namespace/networks/ingress",
      },
      {
        name: "ingress",
        hideInMenu: true,
        path: "/kubernetes/cluster/networks/ingresses/create/text",
        component: "./kubernetes/namespace/networks/ingress/text",
      },
      {
        name: "ingress",
        hideInMenu: true,
        path: "/kubernetes/cluster/networks/ingresses/:name/:action",
        component: "./kubernetes/namespace/networks/ingress/form",
      },
      {
        name: "endpoint",
        path: "/kubernetes/cluster/networks/endpoints",
        component: "./kubernetes/namespace/networks/endpoint",
      },
      {
        name: "endpoint",
        hideInMenu: true,
        path: "/kubernetes/cluster/networks/endpoints/:name/:action",
        component: "./kubernetes/namespace/networks/endpoint/text",
      },
      {
        name: "EndpointSlice",
        path: "/kubernetes/cluster/networks/endpoint_slices",
        component: "./kubernetes/namespace/networks/endpoint_slice",
        access: "clusterResourceEndpointSliceAccess",
      },
      {
        name: "EndpointSlice",
        hideInMenu: true,
        path: "/kubernetes/cluster/networks/endpoint_slices/:name/:action",
        component: "./kubernetes/namespace/networks/endpoint_slice/text",
        access: "clusterResourceEndpointSliceAccess",
      },
    ],
  },
  {
    icon: "usergroupAddOutlined",
    name: "access",
    path: "/kubernetes/cluster/access",
    access: "clusterAccess",
    routes: [
      {
        name: "clusterRole",
        path: "/kubernetes/cluster/access/clusterroles",
        component: "./kubernetes/cluster/cluster_role",
        access: "clusterAccess",
      },
      {
        name: "clusterRole",
        hideInMenu: true,
        path: "/kubernetes/cluster/access/clusterroles/:name/:action",
        component: "./kubernetes/cluster/cluster_role/text",
        access: "clusterAccess",
      },
      {
        name: "clusterRoleBinding",
        path: "/kubernetes/cluster/access/clusterrolebindings",
        component: "./kubernetes/cluster/cluster_role_binding",
        access: "clusterAccess",
      },
      {
        name: "clusterRole",
        hideInMenu: true,
        path: "/kubernetes/cluster/access/clusterrolebindings/:name/:action",
        component: "./kubernetes/cluster/cluster_role_binding/text",
        access: "clusterAccess",
      },
      {
        name: "serviceaccount",
        path: "/kubernetes/cluster/access/serviceaccounts",
        component: "./kubernetes/namespace/access/serviceaccount",
        access: "clusterAccess",
      },
      {
        name: "role",
        path: "/kubernetes/cluster/access/role",
        component: "./kubernetes/namespace/access/role",
        access: "clusterAccess",
      },
      {
        name: "rolebinding",
        path: "/kubernetes/cluster/access/rolebinding",
        component: "./kubernetes/namespace/access/rolebinding",
        access: "clusterAccess",
      },
      {
        name: "certificatesigningrequest",
        path: "/kubernetes/cluster/access/certificatesigningrequests",
        component: "./kubernetes/cluster/csr",
        access: "clusterAccess",
      },
      {
        name: "certificatesigningrequest",
        hideInMenu: true,
        path: "/kubernetes/cluster/access/certificatesigningrequests/:name/:action",
        component: "./kubernetes/cluster/csr/text",
        access: "clusterAccess",
      },
    ],
  },
  {
    icon: "DatabaseOutlined",
    name: "storage",
    path: "/kubernetes/cluster/storage",
    access: "clusterAccess",
    routes: [
      {
        name: "storageClass",
        path: "/kubernetes/cluster/storage/storageclass",
        component: "./kubernetes/cluster/storage/storageclass",
        access: "clusterAccess",
      },
      {
        name: "storageClass",
        hideInMenu: true,
        path: "/kubernetes/cluster/storage/storageclass/:name/:action",
        component: "./kubernetes/cluster/storage/storageclass/text",
        access: "clusterAccess",
      },
      {
        name: "persistentVolume",
        path: "/kubernetes/cluster/storage/persistentvolume",
        component: "./kubernetes/cluster/storage/pv",
        access: "clusterAccess",
      },
      {
        name: "persistentVolume",
        hideInMenu: true,
        path: "/kubernetes/cluster/storage/persistentvolume/:name/:action",
        component: "./kubernetes/cluster/storage/pv/text",
        access: "clusterAccess",
      },
      {
        name: "persistentVolumeClaim",
        path: "/kubernetes/cluster/storage/persistentvolumeclaim",
        component: "./kubernetes/namespace/storage/pvc",
        access: "clusterAccess",
      },
      {
        name: "persistentVolumeClaim",
        hideInMenu: true,
        path: "/kubernetes/cluster/storage/persistentvolumeclaim/:name/:action",
        component: "./kubernetes/namespace/storage/pvc/text",
        access: "clusterAccess",
      },
    ],
  },
  {
    icon: "PicRightOutlined",
    name: "policy",
    path: "/kubernetes/cluster/policy",
    access: "clusterAccess",
    routes: [
      {
        name: "networkpolicy",
        path: "/kubernetes/cluster/policy/networkpolicy",
        component: "./kubernetes/namespace/policy/networkpolicy",
      },
      {
        name: "hpa",
        path: "/kubernetes/cluster/policy/hpa",
        component: "./kubernetes/namespace/policy/hpa",
      },
      {
        name: "poddisruptionbudget",
        path: "/kubernetes/cluster/policy/poddisruptionbudgets",
        component: "./kubernetes/namespace/policy/poddisruptionbudget",
      },
    ],
  },

  {
    name: "monitor",
    icon: "EyeOutlined",
    path: "/kubernetes/cluster/monitor",
    access: "clusterAccess",
    routes: [
      {
        name: "event",
        path: "/kubernetes/cluster/monitor/events",
        component: "./kubernetes/namespace/monitor/event",
      },
      {
        name: "auditlog",
        path: "/kubernetes/cluster/monitor/audit",
        component: "./kubernetes/cluster/monitor/audit",
      },
      {
        name: "terminalAuditLog",
        path: "/kubernetes/cluster/monitor/terminal",
        component: "./kubernetes/cluster/monitor/terminal",
      },
    ],
  },

  {
    name: "crd",
    icon: "ProductOutlined",
    path: "/kubernetes/cluster/customresourcedefinitions",
    access: "clusterAccess",
    component: "./kubernetes/crd",
  },
  {
    name: "crd",
    icon: "ProductOutlined",
    hideInMenu: true,
    path: "/kubernetes/cluster/customresourcedefinitions/:name",
    access: "clusterAccess",
    component: "./kubernetes/crd/detail",
  },
  {
    name: "crd",
    icon: "ProductOutlined",
    hideInMenu: true,
    path: "/kubernetes/cluster/customresourcedefinitions/:kind/:group/:version/:plural",
    access: "clusterAccess",
    component: "./kubernetes/crd/instances",
  },
  {
    name: "apiservice",
    icon: "ApiOutlined",
    path: "/kubernetes/cluster/apiservices",
    access: "clusterAccess",
    component: "./kubernetes/cluster/apiservice",
  },
  {
    name: "apiservice",
    icon: "ApiOutlined",
    hideInMenu: true,
    path: "/kubernetes/cluster/apiservices/:name",
    access: "clusterAccess",
    component: "./kubernetes/cluster/apiservice/detail",
  },
  {
    name: "apiservice",
    icon: "ApiOutlined",
    hideInMenu: true,
    path: "/kubernetes/cluster/apiservices/:name/:action",
    access: "clusterAccess",
    component: "./kubernetes/cluster/apiservice/text",
  },
];
